---
title: "Linear_models"
author: "Shumei Liu"
date: "2024-12-02"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

## Import data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

## Fit a model

```{r}
nyc_airbnb |>
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

```{r}
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

## Tidying output

```{r}
fit

summary(fit)
summary(fit)$coef
coef(fit)
```

```{r, include=FALSE}
residuals(fit)
```

Let's look at the result better.

The `broom` package has functions for obtaining a quick summary of the model and for cleaning up the coefficient table.
```{r}
broom::glance(fit)

broom::tidy(fit)
```

```{r}
fit |> 
  broom::tidy() |> 
  select(term, estimate, p.value) |> 
  mutate(term = str_replace(term, "^borough", "Borough: ")) |> 
  knitr::kable(digits = 3)
```

## Diagnostics 诊断

```{r}
modelr::add_residuals(nyc_airbnb, fit)
```

```{r}
modelr::add_predictions(nyc_airbnb, fit)
```

```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = borough, y = resid)) + geom_violin()
```

```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) + geom_point() +
  facet_wrap(. ~ borough)
```

## Hypothesis testing

```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough + room_type, data = nyc_airbnb)
```

```{r}
anova(fit_null, fit_alt) |> 
  broom::tidy()
```

## Nesting data 嵌套数据

```{r}

```











